---
- name: First Ansible playbook
  hosts: local
  become: true

  tasks:
    - name: Ensure Nginx is installed
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: Ensure Nginx is enabled and running
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        state: started